core/urls.py
from django.urls import path
from .views import *

app_name = 'core'


urlpatterns = [
    path('',home,name='home'),
    path('about-page/',about_page,name='aboutus'),
    path('contact/', Contact.as_view() ,name='contact'),
    path('faq/',faq,name='faq'),
    path('search/',search,name='search'),
    path('autosuggestApi/', autosuggestApi ,name='autosuggestApi'),

]

multicart/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('social-auth/', include('social_django.urls', namespace="social")),
]


urlpatterns += i18n_patterns(
    path('orders/',include('orders.urls', namespace='orders')),
    path('account/',include('accounts.urls', namespace='accounts')),
    path('api/', include('accounts.api.urls', namespace='accounts_api')),
    path('api/', include('products.api.urls', namespace='products_api')),
    path('api/', include('orders.api.urls', namespace='orders_api')),
    path('', include('products.urls', namespace='products')),
    path('', include('core.urls' , namespace='core')),
    prefix_default_language=False
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


handler404 = 'core.views.error_404_view'

orders/api/urls.py
from django.urls import path
from .views import CartApi


app_name = 'orders_api'

urlpatterns = [
    path('cart/', CartApi.as_view(), name = 'cart_api'),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'


urlpatterns=[
    path('cart/', cart,name='cart'),
    path('add-cart/', add_cart,name='add-cart'),
    path('checkout/', checkout, name='checkout'),
    path('order-success/<slug:orderid>', order_success,name='order-success'),


]

orders/models.py
from django.db import models
from core.models import *
from django.contrib.auth.models import User
from products.models import Product, PropertyValue,Property
# Create your models here.


class Cart(AbstractModel):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    property=models.ManyToManyField(PropertyValue, related_name='carts')
    quantity=models.IntegerField()
    total_price = models.FloatField()

    def __str__(self):
        return f'{self.user}---{self.product}---{self.quantity}'

    def save(self, *args, **kwargs):
        self.total_price=round(float(self.product.actual_price) * int(self.quantity),2)
        super(Cart, self).save(*args, **kwargs)

class Orders(AbstractModel):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    orderId=models.IntegerField(unique=False)
    quantity=models.IntegerField()
    first_name = models.CharField(max_length=50, null=True, blank=True, default='')
    last_name = models.CharField(max_length=50, null=True, blank=True, default='')
    email = models.CharField(max_length=50, null=True, blank=True, default='')      
    phone_number = models.CharField(max_length=50, null=True, blank=True, default='')
    flat = models.CharField(max_length=50, null=True, blank=True, default='')
    address = models.CharField(max_length=100, null=True, blank=True, default='')
    zip = models.CharField(max_length=50, null=True, blank=True, default='')
    country = models.CharField(max_length=50, null=True, blank=True, default='')
    city = models.CharField(max_length=50, null=True, blank=True, default='')
    region = models.CharField(max_length=50, null=True, blank=True, default='')
    payed = models.IntegerField()
    is_success = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.product}---{self.orderId}---{self.first_name} {self.last_name}'

orders/api/views.py
from orders.models import Cart
from rest_framework.views import APIView
from .serializers import *
from rest_framework.response import Response
from rest_framework import viewsets, permissions

class CartApi(APIView):
    http_method_names = ["get","post"]
    permission_classes = (permissions.IsAuthenticated,)
    def get(self, request, *args, **kwags):
        

        if request.user.is_authenticated:
            cart_products = Cart.objects.filter(user=request.user)
        

        products_list = CartProductsSerializer(cart_products, many = True).data
        return Response(products_list)

orders/views.py
from django.shortcuts import render,redirect,get_list_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy , reverse
from django.contrib.auth import get_user_model
import json
from accounts.models import Profile
from django.http import JsonResponse, Http404, HttpResponse
from .models import Cart, Orders
from products.models import Product, PropertyValue
from django.db.models import Q
from django.conf import settings
import stripe
import random
from datetime import timedelta

stripe.api_key = settings.STRIPE_SECRET_KEY

User = get_user_model()
# Create your views here.
@login_required()
def cart(request):
    return render(request,'cart.html')






import stripe
stripe.api_key = "sk_test_51MT1tpIpI2DRrDde4li8UJBGaNS73zugCRBzco8SHT71xKHy2byY41Aogmnt33dEbAJDWqTAfPs5d5MVTNsCBTcH00Xfdxda1D"



 



@login_required()
def checkout(request):

    context={}


    if request.GET.get('prod', ""):
        user = request.user
        profile = Profile.objects.get(user=request.user)
        products = get_list_or_404(Product , slug=request.GET.get('prod',''))[0]
        amount=products.actual_price * int(request.GET.get('quantity',""))
        if request.method == "POST":
            amount = float(products.actual_price) 
            #Create customer
            try:
                customer = stripe.Customer.create(
                            email=request.user.email,
                            name=request.user.first_name,
                            description="Product payment",
                            source=request.POST['stripeToken']
                            )

            except stripe.error.CardError as e:
                return HttpResponse("<h1>There was an error charging your card:</h1>"+str(e))     

            except stripe.error.RateLimitError as e:
                    # handle this e, which could be stripe related, or more generic
                    return HttpResponse("<h1>Rate error!</h1>")

            except stripe.error.InvalidRequestError as e:
                return HttpResponse("<h1>Invalid requestor!</h1>")

            except stripe.error.AuthenticationError as e:  
                return HttpResponse("<h1>Invalid API auth!</h1>")

            except stripe.error.StripeError as e:  
                return HttpResponse("<h1>Stripe error!</h1>")

            except Exception as e:  
                pass  
            #Stripe charge 
            charge = stripe.Charge.create(
                    customer=customer,
                        amount=int(products.actual_price)*100,
                        currency='usd',
                        description="Product selling"
                    ) 
            transRetrive = stripe.Charge.retrieve(
                        charge["id"],
                        api_key="sk_test_51MT1tpIpI2DRrDde4li8UJBGaNS73zugCRBzco8SHT71xKHy2byY41Aogmnt33dEbAJDWqTAfPs5d5MVTNsCBTcH00Xfdxda1D"
                    )
            charge.save() # Uses the same API Key.

            while True:
                orderId=random.randint(0,100000000)
                if not Orders.objects.filter(orderId=orderId):
                    orderId=random.randint(0,100000000)
                    break

            order = Orders.objects.create(product = products, orderId=orderId, quantity=request.GET.get('quantity',''), first_name=request.POST.get('first_name'),
                                        last_name=request.POST.get('last_name'),email=request.POST.get('email'),phone_number=request.POST.get('phone_number'),
                                        flat=request.POST.get('flat'),address=request.POST.get('address'),zip=request.POST.get('zip'),country=request.POST.get('country',f"{profile.country}"),
                                        city=request.POST.get('city'),region=request.POST.get('region'),payed=amount
            )
            order.save()
            return redirect(f'/orders/order-success/{orderId}')





        
        context={
            'user':user,
            'profile':profile,
            'products':products,
            'amount':amount,
            'quantity':request.GET.get('quantity',""),
            'incart':False
        }
    else:
        user = request.user
        profile = Profile.objects.get(user=request.user)
        products = Cart.objects.filter(user=request.user)
        if request.method == "POST":
            amount = float(request.POST.get('amount')) 
            #Create customer
            try:
                customer = stripe.Customer.create(
                            email=request.POST.get('email'),
                            name=request.POST.get('first_name'),
                            description="Product payment",
                            source=request.POST['stripeToken']
                            )

            except stripe.error.CardError as e:
                return HttpResponse("<h1>There was an error charging your card:</h1>"+str(e))     

            except stripe.error.RateLimitError as e:
                    # handle this e, which could be stripe related, or more generic
                    return HttpResponse("<h1>Rate error!</h1>")

            except stripe.error.InvalidRequestError as e:
                return HttpResponse("<h1>Invalid requestor!</h1>")

            except stripe.error.AuthenticationError as e:  
                return HttpResponse("<h1>Invalid API auth!</h1>")

            except stripe.error.StripeError as e:  
                return HttpResponse("<h1>Stripe error!</h1>")

            except Exception as e:  
                pass  
            #Stripe charge 
            charge = stripe.Charge.create(
                    customer=customer,
                        amount=int(amount)*100,
                        currency='usd',
                        description="Product selling"
                    ) 
            transRetrive = stripe.Charge.retrieve(
                        charge["id"],
                        api_key="sk_test_51MT1tpIpI2DRrDde4li8UJBGaNS73zugCRBzco8SHT71xKHy2byY41Aogmnt33dEbAJDWqTAfPs5d5MVTNsCBTcH00Xfdxda1D"
                    )
            charge.save() # Uses the same API Key.
            while True:
                    orderId=random.randint(0,100000000)
                    if not Orders.objects.filter(orderId=orderId):
                        orderId=random.randint(0,100000000)
                        break
            for i in products:
                order = Orders.objects.create(product = i.product, orderId=orderId, quantity=i.quantity, first_name=request.POST.get('first_name'),
                                            last_name=request.POST.get('last_name'),email=request.POST.get('email'),phone_number=request.POST.get('phone_number'),
                                            flat=request.POST.get('flat'),address=request.POST.get('address'),zip=request.POST.get('zip'),country=request.POST.get('country',f"{profile.country}"),
                                            city=request.POST.get('city'),region=request.POST.get('region'),payed=amount    
                )
                i.delete()
            order.save()
            return redirect(f'/orders/order-success/{orderId}')


        
        amount=float()
        
        for i in products:
            amount+=i.total_price
        context={
            'user':user,
            'profile':profile,
            'products':products,
            'amount':round(amount,2),
            'incart':True
        }

    return render(request,'checkout.html', context)






@login_required()
def order_success(request,orderid):
    orders=Orders.objects.filter(orderId=orderid)
    if orders[0].is_success==False:
        context={}
        country=orders[0].country
        city=orders[0].city
        region=orders[0].region
        flat=orders[0].flat
        address=orders[0].address
        zip=orders[0].zip
        phone_number=orders[0].phone_number
        order_date=orders[0].created_at 
        delivery_date=order_date + timedelta(days=30)
        payed=float(round(orders[0].payed,2))

        context['orders']=orders
        context['orderid']=orders[0].orderId
        context['country']=country
        context['city']=city
        context['region']=region
        context['flat']=flat
        context['address']=address
        context['zip']=zip
        context['phone_number']=phone_number
        context['order_date']=order_date.strftime('%d %B %Y')
        context['delivery_date']=delivery_date.strftime('%d %B %Y')
        context['payed']=payed

        for i in orders:
            i.is_success=True
            i.save()
        

        return render(request,'order-success.html',context)
    else:
        raise Http404

@login_required()    
def add_cart(request):
    if request.method == 'GET':
        raise Http404
    data = json.loads(request.body)
    if not data:
        raise Http404
    action = data['action']
    productId = data['productId']
    quantity = data['quantity']
    size = data['size']
    color = data['color']
    userId = data['userId']
    cart=Cart.objects.filter(user=userId,product=productId,property__values=color.replace(' ',''))
    cart = cart.filter(property__values=size).first()
    if action=='add':
        if not cart:
            cart = Cart.objects.create(user = User.objects.get(id=userId), product=Product.objects.get(id=productId), quantity=quantity)
            cart.property.add(PropertyValue.objects.get(values=size))
            cart.property.add(PropertyValue.objects.get(values=color.replace(' ','')))
            cart.save()
        else:
            cart.quantity+=int(quantity)
            cart.save()
    elif action=='remove':
        if cart:
            cart.delete()     
    elif action=='update':
        if cart:
            cart.quantity=int(quantity)
            cart.save()
  

    return JsonResponse(' ', safe=False)

orders/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load i18n %}




    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>cart</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item active">cart</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class="cart-section section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="items">

                    </div>
                    <table class="table cart-table table-responsive-md">
                        <tfoot id="tfoot">
                            
                        </tfoot>
                    </table>
                </div>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row cart-buttons">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% if LANGUAGE_CODE == 'en' %}
                    <div class="col-6"><a href="/" class="btn btn-solid">continue shopping</a></div>
                    <div id='checkout' class="col-6"><a href="{% url 'orders:checkout' %}" class="btn btn-solid">check out</a></div>
                    {% else %}
                    <div class="col-6"><a href="/az/" class="btn btn-solid">alış verişə davam et</a></div>
                    <div id='checkout' class="col-6"><a href="{% url 'orders:checkout' %}" class="btn btn-solid">ödəniş</a></div>
                    {% endif %}
                    
                </div>
            </form>
        </div>
    </section>
    <!--section end-->

<script>

function main(){

async function Products(api_url='/api/cart') {
    const response = await fetch(api_url, {
        method: 'GET', // *GET, POST, PUT, DELETE, etc.
    });
    
    return response.json(); // parses JSON response into native JavaScript objects
}

Products('/api/cart')
.then((data) => {
    if(data.length>0){
        document.getElementById('items').innerHTML=
`           
<table class="table cart-table table-responsive-xs">
                        <thead>
                            <tr class="table-head">
                                <th scope="col">image</th>
                                <th scope="col">product name</th>
                                <th scope="col">price</th>
                                <th scope="col">quantity</th>
                                <th scope="col">property</th>
                                <th scope="col">total</th>
                                <th scope="col">action</th>
                            </tr>
                        </thead>

                        ${
            (function products() {
              
              var products=[]
                for(i in data){
                    
                    products.push(
                        `
              
                        <tbody>
                            <tr>
                                <td>
                                    <a href="${data[i].product.url}"><img src="${data[i].product.main_img}" alt=""></a>
                                </td>
                                <td>
                                    <a href="${data[i].product.url}">${data[i].product.title}</a>
                                    
                                </td>
                                <td>
                                    <h2>$${data[i].product.actual_price}</h2>
                                </td>
                                <td>
                                    <div class="qty-box">
                                        <div class="input-group">
                                            <input  data-action='update' data-size=${data[i].property[1].values} data-color=${data[i].property[0].values} data-productId=${data[i].product.id} type="number" name="quantity" class="quantity form-control input-number" min="1" value="${data[i].quantity}">
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    ${
                                    (function property() {
                                        propet=[]
                                        for(j in data[i].property){
                                            propet.push(data[i].property[j].values.toUpperCase())
                                        }
                                        return propet
                                    })()}
                                    
                                </td>
                                <td>
                                    <h2 class="td-color">$${data[i].total_price}</h2>
                                </td>
                                <td><button style="background-color: white ;border: none;" data-action='remove' data-size=${data[i].property[1].values} data-color=${data[i].property[0].values} data-productId=${data[i].product.id} class="remove-cart icon"><i class="ti-close"></i></button></td>
                            </tr>
                        </tbody>
                    `
                    )
                }
                return products
            })()
        }


                        
    </table>


`





    var cart_total_price=0;
    for(var i = 0; i<data.length;i++ ){
        cart_total_price+=data[i].total_price
        console.log(data[i].total_price)
    }
    document.getElementById('tfoot').innerHTML=`
                                <tr>
                                <td>total price :</td>
                                <td>
                                    <h2>$${cart_total_price.toFixed(2)}</h2>
                                </td>
                            </tr>`


var removeCartBtn=document.getElementsByClassName('remove-cart')
for(var i = 0; i<removeCartBtn.length;i++){
    removeCartBtn[i].addEventListener('click', function(){
        var productId = this.dataset.productid;
        var action = this.dataset.action;
        var color = this.dataset.color;
        var size = this.dataset.size;
        var quantity = 0;
        removeWishList(productId,action,size,color,quantity)
    })

}

var quant=document.getElementsByClassName('quantity')
for(var i = 0; i<quant.length;i++){
    quant[i].addEventListener('change', function(){
            var productId = this.dataset.productid;
            var action = this.dataset.action;
            var color = this.dataset.color;
            var size = this.dataset.size;
            var quantity = this.value;
            removeWishList(productId,action,size,color,quantity)
        })
}

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var userId='{{request.user.id}}'
function removeWishList(productId,action,size,color,quantity) {
    var url = '/orders/add-cart/'
    fetch(url,{
        method:"POST",
        headers: {
            "X-CSRFToken": getCookie("csrftoken"),
            "Accept": "application/json",
            'Content-Type': 'application/json'
          },
        body:JSON.stringify({'productId':productId,
                             'action':action,
                             'userId':userId,
                             'size':size,
                             'color':color,
                             'quantity':quantity
              
                            })
    })
    .then((response)=>{
        return response.json()
    })
    .then((data)=>{
        console.log(data)
        main()
    })
}

}else{
document.getElementById('items').innerHTML="<h1>You don't have any items</h1>"
document.getElementById('tfoot').innerHTML=''
document.getElementById('checkout').innerHTML='<button disabled style="cursor:default; background-color: #ff4c3b; color: white;padding: 15px;" class="btn btn-solid">check out</button>'
}
});

}

        
main()


</script>
{% endblock %}

orders/templates/order-success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



    <!-- thank-you section start -->
    <section class="section-b-space light-layout">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="success-text"><i class="fa fa-check-circle" aria-hidden="true"></i>
                        <h2>thank you</h2>
                        <p>Payment is successfully processsed and your order is on the way</p>
                        <p>Transaction ID:267676GHERT105467</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Section ends -->


    <!-- order-detail section start -->
    <section class="section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="product-order">
                        <h3>your order details</h3>
                        {% for i in orders %}
                        <div class="row product-order-detail">
                            <div class="col-3"><img src="{{ i.product.main_img.url }}" alt=""
                                    class="img-fluid blur-up lazyload"></div>
                            <div class="col-3 order_detail">
                                <div>
                                    <h4>product name</h4>
                                    <h5>{{ i.product.title }}</h5>
                                </div>
                            </div>
                            <div class="col-3 order_detail">
                                <div>
                                    <h4>quantity</h4>
                                    <h5>{{i.quantity}}</h5>
                                </div>
                            </div>
                            <div class="col-3 order_detail">
                                <div>
                                    <h4>price</h4>
                                    <h5>${{i.product.actual_price}}</h5>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <hr>
                        <div class="final-total">
                            <h3>total <span>${{payed}}</span></h3>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="row order-success-sec">
                        <div class="col-sm-6">
                            <h4>summery</h4>
                            <ul class="order-detail">
                                <li>order ID: {{orderid}}</li>
                                <li>Order Date: {{order_date}}</li>
                                <li>Order Total: ${{payed}}</li>
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <h4>shipping address</h4>
                            <ul class="order-detail">
                                <li>{{country}}</li>
                                <li>{{city}}</li>
                                <li>{{region}}</li>
                                <li>{{flat}}</li>
                                <li>{{address}}, {{zip}}</li>
                                <li>Contact No. {{phone_number}}</li>
                            </ul>
                        </div>
                        <div class="col-sm-12 payment-mode">
                            <h4>payment method</h4>
                            <p>Payment with bankcart</p>
                        </div>
                        <div class="col-md-12">
                            <div class="delivery-sec">
                                <h3>expected date of delivery</h3>
                                <h2>{{delivery_date}}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Section ends -->


{% endblock %}