accounts/api/urls.py
from django.urls import path
from .views import WishListApi


app_name = 'accounts_api'

urlpatterns = [
    path('wishlist/', WishListApi.as_view(), name = 'wishlist_api'),

]

accounts/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'accounts'

urlpatterns=[
    path('profile/', profile,name='profile'),
    path('login/', login_user,name='login'),
    path('logout/', logout_user,name='logout'),
    path('register/', register,name='register'),
    path('forget-pwd/', forget_pwd, name='forget-pwd'),
    path('change-pwd/<token>/', change_pwd, name='change-pwd'),
    path('add-wishlist/', add_wishlist, name='add-wishlist'),
    path('wishlist/', wishlist, name='wishlist'),
    path('subscribe/', subscribe, name='subscribe'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
    activate, name='activate'),

]

htmx_urlpatterns = [

]


urlpatterns += htmx_urlpatterns

core/urls.py
from django.urls import path
from .views import *

app_name = 'core'


urlpatterns = [
    path('',home,name='home'),
    path('about-page/',about_page,name='aboutus'),
    path('contact/', Contact.as_view() ,name='contact'),
    path('faq/',faq,name='faq'),
    path('search/',search,name='search'),
    path('autosuggestApi/', autosuggestApi ,name='autosuggestApi'),

]

multicart/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('social-auth/', include('social_django.urls', namespace="social")),
]


urlpatterns += i18n_patterns(
    path('orders/',include('orders.urls', namespace='orders')),
    path('account/',include('accounts.urls', namespace='accounts')),
    path('api/', include('accounts.api.urls', namespace='accounts_api')),
    path('api/', include('products.api.urls', namespace='products_api')),
    path('api/', include('orders.api.urls', namespace='orders_api')),
    path('', include('products.urls', namespace='products')),
    path('', include('core.urls' , namespace='core')),
    prefix_default_language=False
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


handler404 = 'core.views.error_404_view'

accounts/models.py
from django.db import models
from core.models import AbstractModel
from django.contrib.auth.models import User
from django.db.models.signals import post_save  
from django.dispatch import receiver
from products.models import Product

# Create your models here.




class Profile(AbstractModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=50, null=True, blank=True, default='')
    flat = models.CharField(max_length=50, null=True, blank=True, default='')
    address = models.CharField(max_length=100, null=True, blank=True, default='')
    zip = models.CharField(max_length=50, null=True, blank=True, default='')
    country = models.CharField(max_length=50, null=True, blank=True, default='')
    city = models.CharField(max_length=50, null=True, blank=True, default='')
    region = models.CharField(max_length=50, null=True, blank=True, default='')
    card = models.CharField(max_length=16, null=True, blank=True, default='')
    forget_pwd_token = models.CharField(max_length=100,null=True,blank=True)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def create_profile(sender, **kwargs):
        if kwargs['created']:
            user_profile = Profile.objects.create(user=kwargs['instance'])

    post_save.connect(create_profile, sender=User)
    
class WishList(AbstractModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
class Subscriber(AbstractModel):
    email = models.EmailField()
    

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils.translation import gettext_lazy as _



class RegistrationForm(forms.ModelForm):
    confirm_password = forms.CharField( widget = forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm password'}))
    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password','confirm_password')
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':_('Enter name')
            }),
            'last_name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':_('Enter surname')
            }),
            'username': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':_('Enter username')
            }),
            'email': forms.EmailInput(attrs={
                'class':'form-control',
                'placeholder':_('Enter email')
            }),
            'password': forms.PasswordInput(attrs={
                'class':'form-control',
                'placeholder':_('Enter password')
            })
        }

    def clean(self):
        super().clean()
        if len(self.cleaned_data['password']) < 8:
            self._errors['password'] = self.error_class([_('Should Contain a minimum of 8 characters')])
        if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
            self._errors['confirm_password']  = self.error_class([_('Not same password')])
        if not self.cleaned_data['first_name'].isalpha():
            self._errors['first_name']  = self.error_class([_('Worng first name')])
        if not self.cleaned_data['last_name'].isalpha():
            self._errors['last_name']  = self.error_class([_('Worng last name')])
        if User.objects.filter(email=self.cleaned_data['email']):
            self._errors['email']  = self.error_class([_('This email already exists')])
        if  '@' in self.cleaned_data['username']:
            self._errors['username']  = self.error_class(_(['You cannot use @ in username']))

            

accounts/api/views.py
from accounts.models import WishList
from products.models import Product
from rest_framework.views import APIView
from .serializers import *
from rest_framework.response import Response

class WishListApi(APIView):
    http_method_names = ["get","post"]
    def get(self, request, *args, **kwags):
        

        if request.user.is_authenticated:
            wish_products = WishList.objects.filter(user=request.user)
            products = []
            for product in wish_products:
                products.append(product.product)
        else:
            wishlist_id=[]
            if request.session.get('wishlist'):
                for i in request.session['wishlist']:
                    wishlist_id.append(int(i))
            products=Product.objects.filter(id__in=wishlist_id).distinct()

        

        products_list = ProductsSerializer(products, many = True).data
        return Response(products_list)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import *
import json
from .models import Profile, WishList, Subscriber
from django.contrib import messages
from .helpers import send_forget_pwd,send_activate_link
from django.template.loader import get_template
from django.http import JsonResponse, HttpResponse,Http404
from django.utils.translation import gettext_lazy as _
import uuid
from social_django.models import UserSocialAuth
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_str    
from products.models import Product
from .tokens import account_activation_token
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.
def forget_pwd(request):
    error = ''
    if request.method == "POST":
        email = request.POST.get('email')
        user = User.objects.filter(email=email).first()
        if user and not user.social_auth.exists():
            username = User.objects.get(email=email).username
            user = User.objects.filter(username=username).first()
            token = str(uuid.uuid4())
            profile = Profile.objects.filter(user = user).first()
            profile.forget_pwd_token = token
            profile.save()
            messages.add_message(request, messages.SUCCESS, _("Password reset link sended your email!"))
            send_forget_pwd(user.email, token)
            return redirect(reverse_lazy('core:home'))
        else: error = _('This email not registred')
    return render(request,'forget_pwd.html', context={'error':error})

def change_pwd(request, token):
    get_object_or_404(Profile.objects.filter(forget_pwd_token = token))
    error = []
    profile = Profile.objects.get(forget_pwd_token = token)
    user = User.objects.filter(id=profile.user.id).first()
    if request.method == "POST":
        if len(request.POST['password']) < 3 and request.POST['password'] != request.POST['confirm_password']:
            error.append(_('Should Contain a minimum of 8 characters'))
            error.append(_('Not same password'))
        elif len(request.POST['password']) < 3:
            error.append(_('Should Contain a minimum of 8 characters'))
        elif request.POST['password'] != request.POST['confirm_password']:
            error.append(_('Not same password'))
        else:
            user.set_password(request.POST['password'])
            user.save()
            profile.forget_pwd_token=None
            profile.save()
            messages.add_message(request, messages.SUCCESS, _("Your password changed!"))
            return redirect(reverse_lazy('accounts:login'))
    return render(request, 'change_pwd.html', context={'error':error})

def login_user(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy('accounts:profile'))
    else:
        error = ''
        if request.method == "POST":
            if '@' in request.POST['emailorusername']:
                email = request.POST['emailorusername']
                if User.objects.filter(email=email):
                    username = User.objects.get(email=email).username
                else: username=None
            else:
                username = request.POST['emailorusername']
                if User.objects.filter(username=username):
                    username = request.POST['emailorusername']
                else: username=None
            password = request.POST['password']
            user = authenticate(request, username = username, password = password)
            if user is not None: 
                login(request,user)
                if request.session.get('wishlist'):
                    wishlist=request.session['wishlist']
                    inWishlist = WishList.objects.filter(user=user)
                    for i in wishlist:
                        if not inWishlist.filter(product__id=i):
                            WishList.objects.create(user = user , product=Product.objects.get(id=i))
                    del request.session['wishlist']

                if request.GET.get('next'):
                    messages.add_message(request, messages.SUCCESS, f"{_('Welcome')} {str(username).upper()}!")
                    return redirect(request.GET.get('next'))
                else:
                    messages.add_message(request, messages.SUCCESS, f"{_('Welcome')} {str(username).upper()}!")
                    return redirect(reverse_lazy("accounts:profile"))
            # elif user.is_active=
            else:  error=_('Email or username or password wrong')
        return render(request,'login.html',  context={'error':error})

@login_required()
def logout_user(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS, f"You're logout!")
    return redirect(reverse_lazy('core:home'))

    
def register(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy('accounts:profile'))
    else:
        form = RegistrationForm()
        if request.method == "POST":
            form = RegistrationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.set_password(form.cleaned_data['password'])
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                send_activate_link(user,current_site.domain,urlsafe_base64_encode(force_bytes(user.pk)), account_activation_token.make_token(user),)
                messages.add_message(request, messages.SUCCESS, f"Activation mail sended!")                
                return redirect(reverse_lazy('core:home'))
        return render(request,'register.html', context={'form':form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and not user.is_active and account_activation_token.check_token(user, token)  :
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        if request.session.get('wishlist'):
                    wishlist=request.session['wishlist']
                    inWishlist = WishList.objects.filter(user=user)
                    for i in wishlist:
                        if not inWishlist.filter(product__id=i):
                            WishList.objects.create(user = user , product=Product.objects.get(id=i))
                    del request.session['wishlist']
        messages.add_message(request, messages.SUCCESS, f"Welcome {(user.username).upper()}!")
        return redirect(reverse_lazy('accounts:profile'))
    else:
        raise Http404



@login_required()
def profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    context = {
        'user' : user,
        'profile' : profile,
    }

    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        phone_number = request.POST['phone_number']
        flat = request.POST['flat']
        address = request.POST['address']
        zip = request.POST['zip']
        country = request.POST.get('country')
        city = request.POST['city']
        region = request.POST['region']
        if 'save' in request.POST:
            email_errors = []
            first_name_errors = []
            last_name_errors = []
            phone_number_errors = []
            city_errors = []
            region_errors = []
            username_errors = []
            if first_name != user.first_name and not user.social_auth.exists():
                if not first_name.isalpha():
                    first_name_errors.append(_('Worng first name'))
                else: 
                    user.first_name = first_name

            if last_name != user.last_name and not user.social_auth.exists():
                if not last_name.isalpha():
                    last_name_errors.append(_('Worng last name'))
                else: 
                    user.last_name = last_name

            if username != user.username:
                if User.objects.filter(username=username):
                    username_errors.append(_('This username already exists'))
                elif '@' in username:
                    username_errors.append(_('You cannot use @ in username'))
                else:
                    user.username = username

            if email != user.email and not user.social_auth.exists():
                if User.objects.filter(email=email):
                    email_errors.append(_('This email already exists'))
                else:
                    user.email = email

            if phone_number != profile.phone_number:
                if not phone_number.isdigit() or len(phone_number)<10:
                    phone_number_errors.append(_('Wrong phone number'))
                else:
                    profile.phone_number = phone_number

            if flat != profile.flat: 
                profile.flat = flat

            if address != profile.address:
                profile.address = address

            if zip != profile.zip:
                profile.zip = zip

            if country != profile.country and country != None:
                profile.country = country

            if city != profile.city:

accounts/templates/activation_email.html
{% autoescape off %}

    Hi {{ user.username }},
    Please click on the link below to confirm your registration: http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

{% endautoescape %}

accounts/templates/change_pwd.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title%}ChangePWD | Multikart{% endblock %}</title>
{% block content %}



    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>Change password</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'accounts:login' %}">login</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Change password</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class=" section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <center>
                        <h2>Change Your Password</h2>
                    </center>
                    <form class="theme-form" method="POST" >
                        {% csrf_token %}
                        <div class="form-group">
                            <label>NEW PASSWORD</label>
                            <input name="password" type="password" class="form-control"  placeholder="New Password" required="">
                            {% if error %}
                            <ul>
                                {% for e in error %}
                                <li style="color: red;">{{e}}</li><br>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="review">CONFIRM NEW PASSWORD</label>
                            <input name="confirm_password" type="password" class="form-control" placeholder="Confirm New Password" required="">

                        </div>
                        <center>
                            <button type="submit" class="btn btn-solid">Change</button>
                        </center>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!--Section ends-->

{% endblock %}

accounts/templates/forget_pwd.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title%}ForgetPWD | Multikart{% endblock %}</title>

{% block content %}



    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>forget password</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'accounts:login' %}">login</a></li>
                            <li class="breadcrumb-item active" aria-current="page">forget password</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class="pwd-page section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <h2>Forget Your Password</h2>
                    <form class="theme-form" method="POST">
                        {% csrf_token %}
                        {% if error %}
                        <h4 style="color: red; display: flex; align-items: center; justify-content: center; background-color: rgba(255, 0, 0, 0.226); height: 50px;">{{error|upper}}</h4>
                        {% endif %}
                        <div class="form-row">
                            <div class="col-md-12">
                                <input type="text" class="form-control" name="email" placeholder="Enter Your Email"
                                    required="">
                            </div><button type="submit" class="btn btn-solid">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!--Section ends-->

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title%}Login | Multikart{% endblock %}</title>

{% block content %}



    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>customer's login</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item active">login</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class="login-page section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h3>Login</h3>
                    <div class="theme-card">
                        <form class="theme-form" method="POST" >
                            {% csrf_token %}
                            {% if error %}
                            <h4 style="color: red; display: flex; align-items: center; justify-content: center; background-color: rgba(255, 0, 0, 0.226); height: 50px;">{{error|upper}}</h4>
                            {% endif %}
                            <div class="form-group">
                                <label for="email">email or username</label>
                                <input name="emailorusername" type="text" class="form-control" placeholder="Email Or Username" required="">
                            </div>
                            <div class="form-group">
                                <label for="review">Password</label>
                                <input name="password" type="password" class="form-control" id="email" placeholder="Password" required="">

                            </div>
                            <button type="submit" style="border-right: 1px solid white;"class="btn btn-solid">Login</button><a href="{% url 'accounts:forget-pwd' %}" style="border-left: 1px solid white; "class="btn btn-solid">Forget password</a>
                        </form>
                    </div>
                    <div class="theme-card">
                        <center>
                            <h3 style="margin-top: 10px;">login with</h3>
                            <a href="{% url 'social:begin' 'facebook' %}?next={{ request.GET.next }}"><img width="40px" height="40px" src="{% static 'assets/images/Facebook_Logo_(2019).png' %}" alt=""></a>
                            <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.GET.next }}"><img width="50px" height="50px" src="{% static 'assets/images/google-logo-png-webinar-optimizing-for-success-google-business-webinar-13.png' %}" alt=""></a>
                        </center>
                    </div>
                    
                </div>
                <div class="col-lg-6 right-login">
                    <h3>New Customer</h3>
                    <div class="theme-card authentication-right">
                        <h6 class="title-font">Create A Account</h6>
                        <p>Sign up for a free account at our store. Registration is quick and easy. It allows you to be
                            able to order from our shop. To start shopping click register.</p><a href="{% url 'accounts:register' %}"
                            class="btn btn-solid">Create an Account</a>
                    </div>
                </div>
            </div>
        </div>
    </section>      
    <!--Section ends-->

{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title%}Register | Multikart{% endblock %}</title>

{% block content %}





    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>create account</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">create account</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class="register-page section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3>create account</h3>
                    <div class="theme-card">
                        <form class="theme-form" action="{% url 'accounts:register' %}" method="POST">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label for="email">First Name</label>
                                    {{form.first_name}}
                                <ul>
                                    {% for error in form.first_name.errors %}
                                    <li style="color: red;">{{error}}</li>
                                    {% endfor %}
                                </ul>
                                </div>
                                <div class="col-md-6">
                                    <label for="review">Last Name</label>
                                    {{form.last_name}}
                                    <ul>
                                        {% for error in form.last_name.errors %}
                                        <li style="color: red;">{{error}}</li>
                                        {% endfor %}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label for="email">username</label>
                                    {{form.username}}
                                    <ul>
                                        {% for error in form.username.errors %}
                                        <li style="color: red;">{{error}}</li>
                                        {% endfor %}
                                </div>
                                <div class="col-md-6">
                                    <label for="email">email</label>
                                    {{form.email}}
                                    <ul>
                                        {% for error in form.email.errors %}
                                        <li style="color: red;">{{error}}</li>
                                        {% endfor %}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label for="email">password</label>
                                    {{form.password}}
                                    <ul>
                                        {% for error in form.password.errors %}
                                        <li style="color: red;">{{error}}</li>
                                        {% endfor %}
                                </div>
                                <div class="col-md-6">
                                    <label for="email">confirm password</label>
                                    {{form.confirm_password}}
                                    <ul>
                                        {% for error in form.confirm_password.errors %}
                                        <li style="color: red;">{{error}}</li>
                                        {% endfor %}
                                </div>
                                <button type="submit" class="btn btn-solid">create Account</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Section ends-->

{% endblock %}